dependencies {
    // Registrate
    api(libs.registrate)

    // Anvil Lib
    implementation(libs.anvillib)
    interfaceInjectionData(libs.anvillib)

    // AnvilCraft
    implementation(libs.anvilcraft) { transitive = false }
    interfaceInjectionData(libs.anvilcraft) { transitive = false }

    // KubeJS
    implementation(libs.rhino){ transitive = false }
    implementation(libs.kubejs){ transitive = false }
}