dependencies {
    // Anvil Lib
    runtimeOnly(libs.anvillib)
    compileOnly(libs.bundles.anvillib)
    interfaceInjectionData(libs.anvillib.recipe)
    interfaceInjectionData(libs.anvillib.moveableEntityBlock)

    // AnvilCraft
    implementation(libs.anvilcraft) { transitive = false }
    interfaceInjectionData(libs.anvilcraft) { transitive = false }

    // KubeJS
    implementation(libs.rhino){ transitive = false }
    implementation(libs.kubejs){ transitive = false }

    // ProbeJS
    runtimeOnly(libs.probejs)
}